services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - auth-localstack
      - auth-redis
    environment:
      NODE_ENV: prod
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  auth-redis:
    image: redis
    ports:
      - '6379:6379'

  auth-localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data